### PR TITLE
fix: `Parse.Query` throws error when no response header

### LINKED ISSUE #2753: Parse.query() raises`Uncaught (in promise) Error: Failed to execute 'has' on 'Headers': Invalid name`
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

If any of the Parse.find queries are executed, an `Uncaught (in promise) Error: Failed to execute 'has' on 'Headers': Invalid name` exception is raised when the request is received.

### Steps to reproduce

1. Fetch a parse.min.js
```html
    <script type="text/javascript" src="https://unpkg.com/parse/dist/parse.min.js"></script>
```

2. Initialization

```javascript
  Parse.initialize(id, token);
  Parse.serverURL = 'https://parseapi.back4app.com/';
```

3. Run a query

```javascript
    const refQuery = new Parse.Query(SomeSchemaName);
    refQuery
      .equalTo('someParam', someParamValue).limit(1000);
      .find() // without `find()` or any filter, the error be raised too
      .then((results) => {
        // ...
      })
      .catch((error) => {
        // The error will be raised
      });
```

### Actual Outcome

`Uncaught (in promise) Error: Failed to execute 'has' on 'Headers': Invalid name` thrown at the below header check.

https://github.com/parse-community/Parse-SDK-JS/blob/7bec0fd472762883fb8a2beb430e749b1b950d48/src/RESTController.ts#L161

### Expected Outcome

Query result will be retrieved.

###  Environment

Server
- Parse Server version: 6.2.0
- Operating system: not disclosed
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Back4App

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 3.6.0
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Back4App

Client
- Parse JS SDK version: 7.0.0
- Chrome Version 141.0.7390.108 (Official Build) (arm64)
- MacOS 26.0.1

### Logs
**Parse server response**

Image

Image

**Client debug log**

Image

### PR DESCRIPTION
**Pull request by Niccari**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Closes: #2753

## Approach

When parsing response headers in RESTController, the header key check is no longer performed if there are no headers.

To ensure this issue can be detected, the unit test `mockFetch` was updated to throw an exception—just like the actual runtime—when an empty string is passed to `headers.has`.

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

## Summary by CodeRabbit

- **Bug Fixes**
  - Avoid checking empty header names when reading response headers, reducing errors and improving stability when handling exposed headers.

- **Tests**
  - Test helpers now raise a clear TypeError for empty header names.
  - Added tests to confirm AJAX requests succeed when the exposed-headers value is missing or empty.

### CODE REVIEW

**Comment by parseplatformorg** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/acinader/pr-checks/d548d96c-6e01-45f6-b697-384481e32b8f?refs=1854232199785d76d2c853d350cd9b65e28952c5&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

**Review by kinetifex — APPROVED** [review]
Encountered this also

**Comment by mtrezza** [comment]
@Niccari could you add a test?

**Comment by Niccari** [comment]
> @Niccari could you add a test?

OK, I've added an explicit test at [4397cb1](https://github.com/parse-community/Parse-SDK-JS/pull/2754/commits/4397cb168302c3ffa69160e34bda4c00c191a552).

Note that the previous mockFetch did not throw an exception if the value of header.has was empty, but commit 5359aa88a5752b52d501cd73862da61055b02d69 changed it to throw an exception just like the actual runtime.

File: src/__tests__/test_helpers/mockFetch.js [hunk 1]
```diff
@@ -25,7 +25,12 @@ function mockFetch(results, headers = {}, error) {
       },
       headers: {
         get: header => headers[header],
-        has: header => headers[header] !== undefined,
+        has: header => {
+          if (header === '') {
+            throw new TypeError('Headers.has: "" is an invalid header name.');
```
Comment (mtrezza) [inline src/__tests__/test_helpers/mockFetch.js:30]:
```suggestion
            throw new TypeError('Invalid empty header name.');
```

**Comment by mtrezza** [comment]
Looks good, but waiting for more details in https://github.com/parse-community/Parse-SDK-JS/issues/2753#issuecomment-3445399383 for proper changelog entry.

File: src/__tests__/test_helpers/mockFetch.js [hunk 2]
```diff
@@ -25,7 +25,12 @@ function mockFetch(results, headers = {}, error) {
       },
       headers: {
         get: header => headers[header],
-        has: header => headers[header] !== undefined,
+        has: header => {
+          if (header === '') {
+            throw new TypeError('Invalid empty header name.');
```
Comment (mtrezza) [inline src/__tests__/test_helpers/mockFetch.js]:
```suggestion
            throw new TypeError('Headers.has: "" is an invalid header name.');
```

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
Thanks for the PR! Waiting for CI to pass...

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.2-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/7.0.2-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/7.0.2)
