### PR TITLE
fix: `ParseUser.linkWith` doesn't remove anonymous auth data

### LINKED ISSUE #1353: User.linkWith doesn't remove anonymous auth
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Calling user.linkWith() server-side doesn't remove the "anonymous" field from the authData object field, causing Parse.AnonymousUtils to still report the user as an Anonymous user.

### Steps to reproduce

````js
Parse.Cloud.define('linkWithAccount', async (request) => {
  const user = request.user;
  if (!user) throw 'NoUser';
  const provider = request.params.provider as string;
  const authData = request.params.authData as any;
  if (!provider) throw 'NoProvider';
  else if (!authData) throw 'NoAuthData';

  await user.linkWith(provider, { authData }, {
    useMasterKey: true,
    sessionToken: user.getSessionToken()
  });
  
  return { ok: true };
});
````

### Actual Outcome

The authData field on Parse Database still has the "anonymous" field, resulting in Parse.AnonymousUtils to still report the user as an Anonymous user
````
{
  "anonymous": {
    "id": "<random-string>"
  },
  "<linked_service_name>": {
    ...linked_service_data
  }
}
````

### Expected Outcome

Inpecting the authData field on Parse Database not have the anonymous field (should only have..)
````
{
  "<linked_service_name>": {
    ...linked_service_data
  }
}
````
### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `4.5.0`
- Operating system: `Mac OS X Mojave 10.14.6`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Javascript (React-Native)`
- SDK version: `2.19.0`

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Calling user.linkWith() doesn't remove the "anonymous" field from the authData object field, causing Parse.AnonymousUtils to still report the user as an Anonymous user.

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1353

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mtrezza** [comment]
Could this be a breaking change?

**Comment by dplewis** [comment]
I don’t think so since it’s a port from the Objective-C SDK and every other SDK has it.

I’m more curious how the server acted before this with anonymous data always there if the developer used JS only.

**Comment by dplewis** [comment]
This also fixes an issue, if the linkWith fails the authData was still stored locally / internally to the user.

File: integration/test/ParseUserTest.js [hunk 1]
```diff
@@ -979,11 +979,11 @@ describe('Parse User', () => {
     await Parse.FacebookUtils.link(user);
 
     expect(Parse.FacebookUtils.isLinked(user)).toBe(true);
-    expect(Parse.AnonymousUtils.isLinked(user)).toBe(true);
+    expect(Parse.AnonymousUtils.isLinked(user)).toBe(false);
```
Comment (mtrezza) [inline integration/test/ParseUserTest.js:982]: It's interesting though that there is even a test case that expects anonymous user to be `true` after `linkWith`. Did you take a look at the commit history / PR that added the test, so see if that was deliberately, or just a mistake?

Comment (mtrezza) [reply integration/test/ParseUserTest.js:982]: Never mind, I just noticed that you were also the author if this test in https://github.com/parse-community/Parse-SDK-JS/commit/ba6c448d4c79ceff7ceda54edcf1712d90e2d5d0. There is no further history to it, nor a note in the PR.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.7](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0)
