### PR TITLE
fix: Chrome browser console warning about unsafe header `access-control-expose-headers` when calling Cloud Function

### LINKED ISSUE #2059: Refused to get unsafe header "access-control-expose-headers" on Chrome
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Latest Parse SDK (v4.3.1) from "localhost:4200" raise systematically a chrome error `Refused to get unsafe header "access-control-expose-headers"` when using `Cloud.run(...)` against a Parse-Server also hosted on localhost.
Issue does not exist with Parse SDK v4.3.0.

### Steps to reproduce
Launch a Parse-Server (last version >= v6.4.0).
Use Chrome (or Brave) to make a call to Parse-Server, using the Parse SDK v4.3.1 with the Cloud.run(...) function.

### Actual Outcome
Raise a Chrome error `Refused to get unsafe header "access-control-expose-headers"` for each call using Cloud.run(...)

### Expected Outcome
No error as v4.3.0

###  Environment
NodeJS >= 18

Server
- Parse Server version: `v6.4.0`
- Operating system: `Windows 10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `15.x`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- Parse JS SDK version: `4.3.1`

### PR DESCRIPTION
**Pull request by mortenmo**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

https://github.com/parse-community/Parse-SDK-JS/issues/2059

Closes: #2059

## Approach

Based on https://trackjs.com/blog/refused-unsafe-header/

Chrome shows a console error when accessing a non-existant header. Checking if header is available before calling that method.

### CODE REVIEW

File: src/__tests__/test_helpers/mockXHR.js [hunk 1]
```diff
@@ -19,6 +19,9 @@ function mockXHR(results, options = {}) {
     getRequestHeader: function (key) {
       return headers[key];
     },
+    getAllResponseHeaders: function() {
```
Comment (mtrezza) [inline src/__tests__/test_helpers/mockXHR.js]: Why does this need to be added to the tests?

Comment (mortenmo) [reply src/__tests__/test_helpers/mockXHR.js]: There were about ~40 tests that failed with this error:

`XMLHttpRequest failed: "TypeError: xhr.getAllResponseHeaders is not a function"`

A lot of the tests uses the `RESTController` it looks like with a mocked out `xhr` object (some uses the mockXHR, a lot of others uses their own, could probably be cleaned up) and when it reaches the header check they failed.

Comment (mtrezza) [reply src/__tests__/test_helpers/mockXHR.js]: But the tests already passed previously with that mocked xhr, right?

Comment (mortenmo) [reply src/__tests__/test_helpers/mockXHR.js]: If I take those lines out in this PR, we get the following result:
```
Test Suites: 3 failed, 46 passed, 49 total
Tests:       24 failed, 1047 passed, 1071 total
Snapshots:   0 total
Time:        42.54 s
```

Because `RestController.ts:dispatch()` in this PR needs `getAllResponseHeaders()` to make sure the header exists before calling `getRequestHeader`, that's how it avoids the Chrome error log (like this article suggests https://trackjs.com/blog/refused-unsafe-header/)

Before I did anything, the tests also passed yes if that's what you were asking?

Comment (mtrezza) [reply src/__tests__/test_helpers/mockXHR.js]: Yes, that's what I'm asking - why do we have to modify the tests, if they passed previously?

File: src/RESTController.js [hunk 2]
```diff
@@ -110,11 +110,14 @@ const RESTController = {
           let response;
           try {
             response = JSON.parse(xhr.responseText);
+            const availableHeaders = xhr.getAllResponseHeaders() || "";
             headers = {};
-            if (typeof xhr.getResponseHeader === 'function' && xhr.getResponseHeader('access-control-expose-headers')) {
+            if (typeof xhr.getResponseHeader === 'function' && availableHeaders.indexOf('access-control-expose-headers') >= 0) {
```
Comment (dplewis) [inline src/RESTController.js]: I think you should add a check for `typeof xhr.getAllResponseHeaders === 'function'`. This reduces the number of changes to the test suite and also check for xhr libraries that don't support getAllResponseHeaders. We have used `getAllResponseHeaders` in the past [here](https://github.com/parse-community/Parse-SDK-JS/pull/2033/files#diff-2a1da7b0f987171bd009d71270bf56a71993e152ffc7f864c58c037517857664L115)

**Review by dplewis — CHANGES_REQUESTED** [review]

File: src/RESTController.js (hunk 2 above)
Comment (mortenmo) [reply src/RESTController.js]: would you just ignore headers completely then if `xhr.getAllResponseHeaders !== 'function'` ?

Comment (mortenmo) [reply src/RESTController.js]:
```
const availableHeaders = typeof xhr.getAllResponseHeaders === 'function' ? xhr.getAllResponseHeaders() : "";
```
?

File: src/__tests__/test_helpers/mockXHR.js (hunk 1 above)
Comment (mortenmo) [reply src/__tests__/test_helpers/mockXHR.js]: RESTController now requires it. but if we do the other suggested change I guess these test changes aren't needed.

File: src/RESTController.js (hunk 2 above)
Comment (dplewis) [reply src/RESTController.js]: This should get rid of `TypeError: xhr.getAllResponseHeaders is not a function` message your seeing. Now you can revert the tests and only mock `getAllResponseHeaders` where you need it.

**Comment by onpix** [comment]
Looking forward to seeing this error fixed!

**Comment by lortonx** [comment]
bump

**Comment by dplewis** [comment]
@mortenmo any updates?

**Comment by mortenmo** [comment]
Thanks for the reminder it fell off my mind. Should be updated with your suggestions.

File: src/RESTController.js [hunk 3]
```diff
@@ -110,11 +110,14 @@ const RESTController = {
           let response;
           try {
             response = JSON.parse(xhr.responseText);
+            const availableHeaders = typeof xhr.getAllResponseHeaders === 'function' ? xhr.getAllResponseHeaders() : "";
             headers = {};
-            if (typeof xhr.getResponseHeader === 'function' && xhr.getResponseHeader('access-control-expose-headers')) {
+            if (typeof xhr.getResponseHeader === 'function' && availableHeaders && availableHeaders.indexOf('access-control-expose-headers') >= 0) {
```
Comment (dplewis) [inline src/RESTController.js]:
```suggestion
            if (typeof xhr.getResponseHeader === 'function' && availableHeaders?.indexOf('access-control-expose-headers') >= 0) {
```
@mortenmo Quick nit

**Review by dplewis — CHANGES_REQUESTED** [review]

**Comment by REPTILEHAUS** [comment]
Really looking forward to this being merged

**Review by mtrezza — COMMENTED** [review]
Is it possible to add a test for this change?

**Comment by mortenmo** [comment]
I wrote some tests. One mimicking the Chrome issue causing the log error. It fails if you revert RESTController and succeeds in this branch.

File: src/__tests__/RESTController-test.js [hunk 4]
```diff
@@ -253,6 +259,63 @@ describe('RESTController', () => {
...
+    await RESTController.request('GET', 'classes/MyObject', {}, {});
+    expect(XHR.prototype.getResponseHeader.mock.calls.length).toBe(0);
+
+    XHR.prototype.getAllResponseHeaders = jest.fn();
+    await RESTController.request('GET', 'classes/MyObject', {}, {});
+    expect(XHR.prototype.getAllResponseHeaders.mock.calls.length).toBe(1);
+    expect(XHR.prototype.getResponseHeader.mock.calls.length).toBe(0);
+  });
+
+  it('mimic chromes console error on getResponseHeader', async () => {
```
Comment (mtrezza) [inline src/__tests__/RESTController-test.js]:
```suggestion
  it('mimics Chrome browser console error on getResponseHeader', async () => {
```

File: src/__tests__/RESTController-test.js [hunk 5]
```diff
@@ -253,6 +259,63 @@ describe('RESTController', () => {
     expect(response._headers['X-Parse-Push-Status-Id']).toBe('5678');
   });
 
+  it('Dont call getRequestHeader with no headers or no getAllResponseHeaders', async () => {
```
Comment (mtrezza) [inline src/__tests__/RESTController-test.js]:
```suggestion
  it('does not call getRequestHeader with no headers or no getAllResponseHeaders', async () => {
```

**Review by mtrezza — CHANGES_REQUESTED** [review]

File: src/__tests__/RESTController-test.js [hunk 6]
```diff
@@ -253,6 +259,63 @@ describe('RESTController', () => {
...
+    await RESTController.request('GET', 'classes/MyObject', {}, {});
+    expect(XHR.prototype.getResponseHeader.mock.calls.length).toBe(0);
+
+    XHR.prototype.getAllResponseHeaders = jest.fn();
+    await RESTController.request('GET', 'classes/MyObject', {}, {});
+    expect(XHR.prototype.getAllResponseHeaders.mock.calls.length).toBe(1);
+    expect(XHR.prototype.getResponseHeader.mock.calls.length).toBe(0);
+  });
+
+  it('mimics Chrome browser console error on getResponseHeader', async () => {
```
Comment (mtrezza) [inline src/__tests__/RESTController-test.js]:
```suggestion
  it('does not invoke Chrome browser console error on getResponseHeader', async () => {
```

**Review by mtrezza — CHANGES_REQUESTED** [review]

**Review by mtrezza — APPROVED** [review]
Looks good, waiting for CI to pass...

**Comment by mtrezza** [comment]
Could you just fix the lint errors?

**Comment by mtrezza** [comment]
There are still 2 open conversations, could you please reply there to see whether they can be closed?

File: src/__tests__/test_helpers/mockXHR.js (hunk 1 above)
Comment (mortenmo) [reply src/__tests__/test_helpers/mockXHR.js]: We reverted this to not require it anymore.

**Comment by mortenmo** [comment]
> There are still 2 open conversations, could you please reply there to see whether they can be closed?

Done

**Comment by mtrezza** [comment]
Thanks for closing the conversations.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.5](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0)
