### PR TITLE
fix: `Parse.User.signUp()` does not pass context to Cloud Code 

### LINKED ISSUE #1526: Cannot pass `context` to signup
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Context can be passed to `user.save`, but does not get passed to server on `user.signUp`

### Steps to reproduce

Pass context to `user.signup`

### Actual Outcome

Context is empty in cloud code

### Expected Outcome

Context should pass

###  Environment

Server
- Parse Server version: `alpha`
- Operating system: `macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `n/a`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `n/a`

Client
- Parse JS SDK version: `3.4.3`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

`context` object isn't passed to `signup`.

Related issue: #1526

### Approach

Pass context object

### TODOs before merging

- [x] Add tests

### CODE REVIEW

File: src/ParseUser.js [hunk 1]
```diff
@@ -425,6 +425,9 @@ class ParseUser extends ParseObject {
     if (options.hasOwnProperty('installationId')) {
       signupOptions.installationId = options.installationId;
     }
+    if (options.hasOwnProperty('context') && typeof options.context === 'object') {
```
Comment (mtrezza) [inline src/ParseUser.js]: `typeof options.context === 'object'` would pass for many types, even `new String()`.

A more specific test would be `Object.prototype.toString.call(context) === '[object Object]'`

**Review by mtrezza — CHANGES_REQUESTED** [review]

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.4-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.4-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0)
